### ISSUE TITLE
[Bug] Zenoh-bridge-dds sometimes does not route DDS or Zenoh topic

### ISSUE THREAD

**Issue by boyu-hang** [eclipse-zenoh/zenoh-plugin-dds#161]
### Describe the bug

We are investigating whether two ROS2 nodes(a publisher and a subscriber) located in different virtual networks could communicate with each other via Zenoh(brokered topology- client mode) when they are all containerized in separate Docker containers.  

The containers and virtual networks are set up using a docker compose file. The case illustration is shown:<img width="954" alt="截屏2023-11-11 19 01 46" src="https://github.com/eclipse-zenoh/zenoh-plugin-dds/assets/147883209/67a4ca02-6c55-436c-ab4b-9523c4177263">
We have executed the case several times. The results we got varied randomly. At times it worked well with the subscriber successfully receiving message, while sometimes it failed because one of the zenoh bridges did not route DDS topic to Zenoh, or Zenoh to DDS though they had already connected to the router. 
The logs from both Zenoh-bridge-dds(one successfully routing topics, the other not):
<img width="1226" alt="截屏2023-11-11 21 00 14" src="https://github.com/eclipse-zenoh/zenoh-plugin-dds/assets/147883209/456b8efa-f672-40b6-8342-11eaf4114ea1">

### Our attempts
1. We guessed that zenoh bridges might not be ready to "work" since docker compose starts containers simultaneously. Thus we start each container one after another in the specified order(publisher->bridge 1->subscriber->bridge 2) and wait for each container to be ready befor starting the next one, but the issue persists 
2.  When we use `docker compose up` to execute all containers for the first time and it fails, pressing `ctrl+c` to stop containers and then executing `docker compose up` to start containers again surprisingly resolves the issue(this is not what we want)

Do you have any ideas why this problem might occur?

### To reproduce

start: name file as `docker-compose.yml` and execute the command `docker compose up`
Docker compose file:
```
services:
  talker:
    image: osrf/ros:iron-desktop
    command: ros2 run demo_nodes_cpp talker
    networks:
      - rosnet-1
  listener:
    image: osrf/ros:iron-desktop
    command: ros2 run demo_nodes_cpp listener
    depends_on:
      - talker
    networks:
      - rosnet-2
  zenoh-router:
    image: eclipse/zenoh
    ports:
      - 7447:7447
    networks:
      - protocolnet-1
      - protocolnet-2
  zenoh-bridge-dds-1:
    image: eclipse/zenoh-bridge-dds
    command: -m client -e tcp/zenoh-router:7447
    networks: 
      - rosnet-1
      - protocolnet-1
    depends_on:
      - zenoh-router
  zenoh-bridge-dds-2:
    image: eclipse/zenoh-bridge-dds
    command: -m client -e tcp/zenoh-router:7447
    networks: 
      - rosnet-2
      - protocolnet-2
    depends_on:
      - zenoh-router

networks:
  rosnet-1:
  rosnet-2:
  protocolnet-1:
  protocolnet-2:
```

### System info

Platform: Ubuntu 20.04 64-bit
Zenoh: 0.10.0-rc
ROS2:iron
Docker:  Docker Engine - Community(version 24.0.5 )
